flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- pretty-terminal-0.1.0.0
- git: https://github.com/OctopiChalmers/BinderAnn
  commit: fcae12a50c8b105f48b575b0787107752a170ec3
- git: https://github.com/maciej-bendkowski/buffon-machines
  commit: 6a98e5437e6a4d9b0b3c1e78532839fdac0325ba # 1.2.0.0
- git: https://github.com/maciej-bendkowski/paganini-hs
  commit: 941e8f6314ea49b79c2cf1a03924cbedc981917e

resolver: lts-14.18
